// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iwbovotspbuhbkokvzna.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3Ym92b3RzcGJ1aGJrb2t2em5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MDI0NjgsImV4cCI6MjA3MTI3ODQ2OH0.Bl_go3X_MaloJyW8RQ5Mo_fR-YdMS5DFImrfaLRAnTE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});